<template>
  <article>
    <header class="pb-16 mb-16 border-b-2 border-white">
      <h1 class="mb-8">Privacy Policy</h1>
      <p><strong>Effective Date:</strong> 9<sup>th</sup> March 2025</p>
      <p><strong>Last Updated:</strong> 9<sup>th</sup> March 2025</p>
      <p>Welcome to <strong>Accessible Web Media</strong> ("we," "us," or "our"). We are committed to protecting your privacy and ensuring transparency about how we handle your personal data.</p>
      <p class="mb-0">If you have any questions, contact us at <a href="mailto:contact@jackchristian.uk">contact@jackchristian.uk</a>.</p>
    </header>
    <main>
      <section>
        <h2>1. What Data We Collect</h2>
        <ul>
          <li><strong>Account Information:</strong> If you sign up using Google or GitHub OAuth, we collect your email, name, and any other details provided by those services.</li>
          <li><strong>User-Generated Content:</strong> We store video and audio transcripts generated by our AI services, but we do <strong>not</strong> store the original media files.</li>
          <li><strong>Analytics Data:</strong> We use Google Analytics to track user interactions and engagement.</li>
          <li><strong>Feedback Data:</strong> If you submit feedback through our form, we store your responses. If you consent, we may use your email to send updates about new features.</li>
        </ul>
      </section>
      <section>
        <h2>2. How We Collect Your Data</h2>
        <ul>
          <li><strong>OAuth Authentication:</strong> When you sign up via Google or GitHub.</li>
          <li><strong>Google Analytics:</strong> Automatically tracking user behavior and engagement.</li>
          <li><strong>User Input:</strong> When you submit feedback through our form.</li>
          <li><strong>Supabase:</strong> Where we store your account information and generated transcripts.</li>
        </ul>
      </section>
      <section>
        <h2>3. How We Use Your Data</h2>
        <ul>
          <li>Provide access to our platform and allow you to sign in with Google or GitHub.</li>
          <li>Generate transcripts and alt text for media files you upload.</li>
          <li>Improve our services based on user feedback.</li>
          <li>Track engagement and improve the user experience using Google Analytics.</li>
          <li>Send feature updates (only if you have consented via the feedback form).</li>
        </ul>
      </section>
      <section>
        <h2>4. Third-Party Services We Use</h2>
        <p>We share your data with the following services <strong>only as necessary</strong>:</p>
        <ul>
          <li><strong>Google Analytics</strong> (tracking user engagement)</li>
          <li><strong>Supabase</strong> (storing user data and transcripts)</li>
          <li><strong>Deepgram</strong> (AI-generated transcription)</li>
        </ul>
        <p>We do <strong>not</strong> sell, rent, or trade your personal information.</p>
      </section>
      <section>
        <h2>5. How Long We Keep Your Data</h2>
        <ul>
          <li>Your account data is stored as long as you have an active account.</li>
          <li>Your transcripts are stored in our system until you delete them.</li>
          <li>If you delete your account, all your data will be permanently deleted, except for any feedback form responses.</li>
        </ul>
      </section>
      <section>
        <h2>6. Your Rights (GDPR, CCPA, Australia)</h2>
        <h3>For EU & UK Users (GDPR Compliance)</h3>
        <ul>
          <li>Access, update, or delete your personal data</li>
          <li>Request a copy of your data</li>
          <li>Withdraw consent for data processing</li>
          <li>Object to automated decision-making</li>
        </ul>
        <h3>For California Users (CCPA Compliance)</h3>
        <ul>
          <li>Know what data we collect and how we use it</li>
          <li>Request that we delete your personal data</li>
          <li>Opt out of the sale of personal data (we do <strong>not</strong> sell data)</li>
        </ul>
        <h3>For Australian Users</h3>
        <ul>
          <li>Request access to your data</li>
          <li>Correct or delete your personal information</li>
        </ul>
        <p>To exercise any of these rights, email <a href="mailto:contact@jackchristian.uk">contact@jackchristian.uk</a> or use the account settings page to delete your data.</p>
      </section>
      <section>
        <h2>7. How We Protect Your Data</h2>
        <p>We take security seriously and use <strong>Supabase’s recommended security protocols</strong> to protect your data. These include:</p>
        <ul>
          <li>Encryption of sensitive data</li>
          <li>Secure access controls</li>
          <li>Regular security monitoring</li>
        </ul>
      </section>
      <section>
        <h2>8. Children’s Privacy</h2>
        <p>We do not knowingly collect data from users under <strong>16 years old</strong>. If you believe a child has signed up, please contact us at <a href="mailto:contact@jackchristian.uk">contact@jackchristian.uk</a> to request data deletion.</p>
      </section>
      <section>
        <h2>9. Updates to This Privacy Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will notify users via <strong>email and platform notifications</strong> when changes occur.</p>
      </section>
    </main>
  </article>
</template>

<style scoped>
h2, h3, ul, ol {
  @apply mb-4;
}

li {
  @apply my-2;
}

ul > li {
  @apply list-disc list-inside;
}

section {
  @apply mb-8
}

a {
  @apply underline;
}
</style>